package albums;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.awt.BorderLayout;

import javax.swing.JTabbedPane;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author jexi
 */
public class Chart extends javax.swing.JFrame {
        
    /**
     * Creates new Chart
     */
    public Chart() {
        initComponents();        
    }
                        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 656, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    /**
     * @brief displays chart of artists with >= 10 albums
     */
    public void DisplayPopularArtistsCharts() {                        
        
        setLayout(new BorderLayout());
        
        JTabbedPane tabbedPane = new JTabbedPane();

        ChartPanel chart1Panel = createChartPopularArtists();
        ChartPanel chart2Panel = createPieChartAlbums();
        
        tabbedPane.addTab("Top Artists", chart1Panel);
        tabbedPane.addTab("Total Albums", chart2Panel);
        
        add(tabbedPane, BorderLayout.CENTER);
    }
           
    
    /**
     * @brief create chart based on db data
     * @return 
     */    
    private ChartPanel createChartPopularArtists() {        
        
        final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
                
        try {
            Database db = new Database();
            ResultSet rs = db.getPopularArtists();
            while (rs.next()) {
                String ArtistName = rs.getString(db.get_fld_artist()); // artist name
                Integer ArtistAlbum = rs.getInt("num"); // num of albums
                dataset.addValue(ArtistAlbum, ArtistName, "Albums");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DisplayArtistAlbumsForm.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        JFreeChart barChart = ChartFactory.createBarChart(
                "Top Artists",
                "Artists",
                "Albums",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false);
                
        return new ChartPanel(barChart);
    }
    
    
    
    /**
     * @brief create pie chart based on counting all albums 
     * @return 
     */
    private ChartPanel createPieChartAlbums() {
        
        final DefaultPieDataset dataset = new DefaultPieDataset();
        ResultSet rs;
                
        try {
            Database db = new Database();
            rs = db.CountTotalCD();
            while (rs.next()) {                
                Integer TotalCD = rs.getInt("cnt");
                dataset.setValue("CD", TotalCD);
            }
            rs = db.CountTotalLP();
            while (rs.next()) {                
                Integer TotalLP = rs.getInt("cnt");
                dataset.setValue("LP", TotalLP);
            }
            rs = db.CountTotalMC();
            while (rs.next()) {                
                Integer TotalMC = rs.getInt("cnt");
                dataset.setValue("Cass", TotalMC);
            }            
        } catch (SQLException ex) {
            Logger.getLogger(DisplayArtistAlbumsForm.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        JFreeChart pieChart = ChartFactory.createPieChart(
                "Total Albums",
                dataset, 
                true, 
                true, 
                false);
                
        return new ChartPanel(pieChart);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}