/**
 * @brief installation wizard
 * @author Yannis Exidaridis <jexi@noc.uoa.gr>
 * 
 */ 
package albums;

import javax.swing.JOptionPane;

/**
 *
 * @author yannis
 */
public class Install extends javax.swing.JFrame {

    /**
     * Creates new form Install
     */
    public Install() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDbName = new javax.swing.JLabel();
        jTextFieldDbName = new javax.swing.JTextField();
        jLabelDbUserName = new javax.swing.JLabel();
        jTextFieldDbUserName = new javax.swing.JTextField();
        jLabelDbPassword = new javax.swing.JLabel();
        jTextFieldDbPassword = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter Database Credentials");
        setLocation(new java.awt.Point(300, 200));
        setMaximumSize(new java.awt.Dimension(400, 300));

        jLabelDbName.setText("Database Name:");

        jLabelDbUserName.setText("Database UserName:");

        jLabelDbPassword.setText("Database Password:");

        jButtonOk.setText("Install");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDbPassword)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDbPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDbUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDbUserName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDbName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jTextFieldDbName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addGap(55, 55, 55)
                .addComponent(jButtonCancel)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDbName)
                    .addComponent(jTextFieldDbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDbUserName)
                    .addComponent(jTextFieldDbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDbPassword)
                    .addComponent(jTextFieldDbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOk))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        
        String db_name = jTextFieldDbName.getText().trim();
        String db_username = jTextFieldDbUserName.getText().trim();
        String db_password = jTextFieldDbPassword.getText().trim();
        String db_url = "jdbc:mysql://localhost:3306/" + db_name + "?characterEncoding=UTF-8";
        // create config file
        Config config = new Config();
        
        if (config.CreateConfig(db_url, db_name, db_username, db_password)) {
            JOptionPane.showMessageDialog(null, "Configuration file created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Error during creation of configuration file!", "Error", JOptionPane.WARNING_MESSAGE);
        }
        String url = "jdbc:mysql://localhost:3306/?user=" + db_username + "&password=" + db_password;
        // create new database
        Database db = new Database(url);
        db.CreateDatabase(db_name);
        db.UseDatabase(db_name);
        db.CreateTable();
        
    }//GEN-LAST:event_jButtonOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelDbName;
    private javax.swing.JLabel jLabelDbPassword;
    private javax.swing.JLabel jLabelDbUserName;
    private javax.swing.JTextField jTextFieldDbName;
    private javax.swing.JTextField jTextFieldDbPassword;
    private javax.swing.JTextField jTextFieldDbUserName;
    // End of variables declaration//GEN-END:variables
}
